
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Rhyzza B. Gueco
 */
public class BookingDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingDialog.class.getName());

    /**
     * Creates new form BookingDialog
     */
    class Flight {

        int id;
        String origin;
        String destination;
        String date;
        String time;
        double economyPrice;
        double businessPrice;
        int economySeats;
        int businessSeats;

        Flight(int id, String origin, String destination, String date, String time,
                double economyPrice, double businessPrice, int economySeats, int businessSeats) {
            this.id = id;
            this.origin = origin;
            this.destination = destination;
            this.date = date;
            this.time = time;
            this.economyPrice = economyPrice;
            this.businessPrice = businessPrice;
            this.economySeats = economySeats;
            this.businessSeats = businessSeats;
        }
    }

    private int userId;
    private int flightId;
    private String origin;
    private String destination;
    private String date;
    private String time;
    private double economyPrice;
    private double businessPrice;
    private int economySeats;
    private int businessSeats;

    public BookingDialog(JFrame parent, int userId, int flightId, String origin,
            String destination, String date, String departureTime,
            double economyPrice, double businessPrice,
            int economySeats, int businessSeats) {
        super(parent, "Book Flight", true);
        this.userId = userId;
        this.flightId = flightId;
        this.origin = origin;
        this.destination = destination;
        this.date = date;
        this.time = departureTime;
        this.economyPrice = economyPrice;
        this.businessPrice = businessPrice;
        this.economySeats = economySeats;
        this.businessSeats = businessSeats;
        initComponents();
        setLocationRelativeTo(null);

        spnSeats.addChangeListener(new javax.swing.event.ChangeListener() {
            @Override
            public void stateChanged(javax.swing.event.ChangeEvent e) {
                updateTotalPrice();
            }
        });
        
        setLocationRelativeTo(parent);
        
        lblFlight.setText("Flight: " + origin + " → " + destination + " (" + date + " " + departureTime + ")");
        
        SpinnerNumberModel model = (SpinnerNumberModel) spnSeats.getModel();
        model.setMaximum(getMaxSeats());
        
        updateTotalPrice();
    }

    private int getMaxSeats() {
        String selectedClass = (String) cmbClass.getSelectedItem();
        return selectedClass.equals("Economy Class") ? economySeats : businessSeats;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientColor();
        jLabel1 = new javax.swing.JLabel();
        cmbClass = new javax.swing.JComboBox<>();
        spnSeats = new javax.swing.JSpinner();
        btnProceed = new GradientButton("Proceed");
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFlight = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 248, 231));
        jLabel1.setText("Booking In Sunlight Airlines");

        cmbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy Class", "Business Class" }));
        cmbClass.addActionListener(this::cmbClassActionPerformed);

        //spnSeats.addPropertyChangeListener(this::spnSeats);

        btnProceed.setText("Proceed");
        btnProceed.addActionListener(this::btnProceedActionPerformed);

        jLabel2.setText("Class: ");

        jLabel3.setText("Seats: ");

        lblFlight.setText("Flights: ");

        lblTotal.setText("Total: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFlight)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnProceed)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(lblFlight)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnProceed)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassActionPerformed
        updateSeatsAndPrice();
    }//GEN-LAST:event_cmbClassActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        String selectedClass = (String) cmbClass.getSelectedItem();
        
        String dbClass = selectedClass.equals("Economy Class") ? "Economy" : "Business";
        int seats = (Integer) spnSeats.getValue();
        double price = selectedClass.equals("Economy Class") ? economyPrice : businessPrice;
        double total = seats * price;
        
        String checkQuery = "SELECT " + (selectedClass.equals("Economy Class") ? "economy_seats" : "business_seats")
                + " FROM flights WHERE id = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(checkQuery)) {
            stmt.setInt(1, flightId);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                int available = rs.getInt(1);
                if (seats > available) {
                    JOptionPane.showMessageDialog(this, "Not enough seats available. Only " + available + " seats left.");
                    return;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
            return;
        }
        
        if (total <= 0) {
            JOptionPane.showMessageDialog(this, "Invalid total price.");
            return;
        }
        
        PaymentDialog paymentDialog = new PaymentDialog(this, userId, flightId, dbClass, seats, total);
        paymentDialog.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProceedActionPerformed

    private void updateSeatsAndPrice() {
        String selectedClass = (String) cmbClass.getSelectedItem();
        int maxSeats = selectedClass.equals("Economy Class") ? economySeats : businessSeats;

        SpinnerNumberModel model = (SpinnerNumberModel) spnSeats.getModel();
        model.setMaximum(maxSeats);

        if ((Integer) spnSeats.getValue() > maxSeats) {
            spnSeats.setValue(maxSeats);
        }

        updateTotalPrice();
    }

    private void updateTotalPrice() {
        int seats = (Integer) spnSeats.getValue();
        double price = (cmbClass.getSelectedItem().equals("Economy Class")) ? economyPrice : businessPrice;
        double total = seats * price;
        lblTotal.setText(String.format("Total: $%.2f", total));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProceed;
    private javax.swing.JComboBox<String> cmbClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnSeats;
    // End of variables declaration//GEN-END:variables
}
